name: "Sign"

on:
  workflow_dispatch:
    schedule:
        - cron: "00 23 * * *"
            - cron: "00 10 * * *"

            jobs:
              build-linux:
                  runs-on: ubuntu-latest
                      strategy:
                            max-parallel: 5
                                steps:
                                    - uses: actions/checkout@v3
                                        - name: Set up Python 3.7
                                              uses: actions/setup-python@v3
                                                    with:
                                                            python-version: 3.7
                                                                - name: Install dependencies
                                                                      run: |
                                                                              pip install requests
                                                                                  - name: Start sign
                                                                                        env:
                                                                                                USERS: ${{ secrets.USERS }}
                                                                                                      run: |
                                                                                                              python main.py
                                                                                                              
